export enum RouteName {
    // ROOT = "/",
    LOGIN = "/",
    REGISTER = "/register",
    DASHBOARD = "/dashboard",
    FORUM = "/forum",
    LESSONS = "/lessons",
    LIBRARY = "/library",
    MYSECTION = "/my-section",
    SETTING = "/setting",
    BOOKMARK = "/bookmark",
    CREATE_ARTICLE = "/create-article",
    UPLOAD_LIBRARY = "/upload-to-library",
    CREATE_LESSONS = "/create-lessons",
    SINGLE_POST = "/single-post",
    MODIFY_ARTICLE = "/single-post/create-article",
    SINGLE_LIBRARY = "/library/book",
    SINGLE_LESSONS = "/lessons/single-view",
}